pretranslate:
  segments:
    ignore_frontmatter_keys:
    - " layout"
    - " title"
    - " description"
    - " hero"
    - " authors"
    - " date"
    - " updated"
    - " tags"
    
    ignore_patterns:
      - !ruby/regexp /{%\s?([a-zA-Z0-9\.\-\?\'\"\,\!\s\/]*)\s?%}/
      - !ruby/regexp /{%\s?end([a-zA-Z0-9\.\-\?\'\"\,\!\s]*)\s?%}/
      - !ruby/regexp /{%\s?AssessmentCallout([a-zA-Z0-9\.\-\?\'\"\,\!\s]*)\s?%}/
